name: GitHub Self-Updating Repository

on:
  schedule:
    - cron: "20 1 * * *"  # Runs daily at 06:50 IST (01:20 UTC)

permissions:
  contents: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Modify README with current IST time
        run: |
          export TZ=Asia/Kolkata
          echo "Current IST Time: $(date)" > README.md
          cat README.md
        timeout-minutes: 2

      - name: Push to repository
        run: |
          git config --global user.name "Jayesh Puri"
          git config --global user.email "jayeshkpuri@gmail.com"
          now=$(TZ=Asia/Kolkata date)
          git add -A
          git commit -m "Auto Push on $now" || echo "Nothing to commit"
          git push
